config:
  target: "http:/"
  plugins:
    expect: {}
  phases:
    - duration: 35
      arrivalRate: 1
      maxVusers: 1
  defaults:
    headers:
      authorization: "a"
  processor: "./functions.js"
  payload:
    path: "./mockData/paramManagement.csv"
    fields:
      - key
      - full_description
      - short_description
      - unit
      - unit_abbreviation
      - type
      - active
    order: sequence
    delimiter: ","
    skipHeader: true

scenarios:
  - name: "POST create param"
    flow:
      - log: "POST Login"
      - post:
          url: "/pm-user-management:3000/api/v1/auth/login"
          json:
            username: "adriana"
            password: "123456"
          capture:
            - json: "$.token.access_token"
              as: "auth_token"
          expect:
            - statusCode: 200
            - contentType: json
            - hasProperty: token
      - log: "POST create param: {{key}}"
      - post:
          url: "/system-management:8080/sm/api/v1/param-management/params"
          headers:
            authorization: "Bearer {{ auth_token }}"
          json:
            key: "{{ key }}"
            full_description: "{{ full_description }}"
            short_description: "{{ short_description }}"
            unit: "{{ unit }}"
            unit_abbreviation: "{{ unit_abbreviation }}"
            type: "{{ type }}"
          capture:
            - json: "$.key"
              as: "keyPost"
          expect:
            - statusCode: 201
            - contentType: json
            - hasProperty: key
            - hasProperty: full_description
            - hasProperty: short_description
            - hasProperty: unit
            - hasProperty: unit_abbreviation
            - hasProperty: type
            - equals:
                - "{{ key }}"
                - "{{ keyPost }}"